### ISSUE TITLE
Use show posters directly from thetvdb.com

### ISSUE THREAD

**Issue by danbovey** [danbovey/SonarrPlex#2]
Some users are experiencing issues with the show posters from Sonarr.

**Comment by markus101** [comment]
There really should be no need for this, Sonarr supports fetching images using Forms/Basic and API key authentication which should take care of any issues. Fetching images directly from TheTVDB even with caching should be avoided. Sonarr also serves up resized images (as long as the system running Sonarr supports it) to reduce bandwidth.

**Comment by danbovey** [comment]
Thanks for taking a look at this!

The API only documents [one URL for each image type](https://github.com/Sonarr/Sonarr/wiki/Series#returns-jsonarray) so it looked quite limited as far as I could see. Got any documentation on images or potential query params that the url takes?

**Comment by markus101** [comment]
If you prefix the URL with /api/ (offhand I don't recall if it's already prefixed with the URL Base or not) it will use API key authentication instead of basic/forms.

For sizes you can replace `.jpg ` with `-250.jpg` where `250` is the height, if no resized image is available at that size you get the full sized image back. There are two different heights for each image type, which are in code here: https://github.com/Sonarr/Sonarr/blob/816cf608fcef07e375aa750a863d0a7365108981/src/NzbDrone.Core/MediaCover/MediaCoverService.cs#L121

I'll take a look at the docs and get them updated.
