### ISSUE TITLE
Sonarr icon and page disappears after few seconds

### ISSUE THREAD

**Issue by alberto467** [danbovey/SonarrPlex#3]
Everything seems to work fine, i can even open the Sonarr page in Plex by clicking on the icon, but after a few second from the refresh of the Plex page everything disappears and i'm sent back to the Plex status page for no reason. This doesn't always happens, one times over 50 refreshes the icon and Sonarr page remained fine, and another time the icon disappeared but the Sonarr page still remained working, it's all very buggy. I tried looking into this, i checked the background page, the JavaScript console and my uBlock Origin. Has someone else had this problem? If you need any logs or information back to investigate this, i'd love to help every way i can.

**Comment by danbovey** [comment]
This extension is a total hack of the Plex app, and it could break at any moment, from any change that the Plex team make. Plex runs in React, it's a bundled js file and as far as I know I can't hook into that to extend the application.

In it's current form the extension, makes a redirect to the status page so that you have the ability to go back to where you were before you clicked the Sonarr icon. Then empties the contents of the page and injects HTML.

The buggy part is probably using `setTimeout` all over the place to initialize the injection of the sonarr icon, which is totally unreliable as we have users loading Plex over different connections and machines.

https://github.com/danbovey/SonarrPlex/blob/master/js/content.js#L10

Could improve this by checking that the navbar has completed filling before dealing with adding the Sonarr button, instead of just guessing that it'll be done in 500ms time.

**Comment by alberto467** [comment]
Definatively helped out, at the time my connection was in heavy use and i was loading the plex web page slowly (the part when you're redirected to the plex.tv domain and then back to the app.plex.tv one). Right now it works out very nicely. Thanks for the great work, keep going and have some nice holidays!

**Comment by danbovey** [comment]
If you're running Sonarr for Plex 1.0.5, which I'm uploading now, the Sonarr button no longer gets removed if Plex makes a change to the navbar.
